services:
  webhook-server:
    build: .
    container_name: webhook-server
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - DB_PATH=/app/data/signals.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8001/api/v1/health', timeout=2); print(r.status_code); exit(0 if r.status_code == 200 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s