services:
  webhook-server:
    build: .
    container_name: webhook-server
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - DB_PATH=/app/data/signals.db
    volumes:
      - ./data:/app/data        # ← локальная папка ./data → /app/data в контейнере
      - ./logs:/app/logs        # ← локальная папка ./logs → /app/logs в контейнере
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s