# docker-compose.yml
version: '3.8'

services:
  webhook-server:
    build: .
    container_name: webhook-server
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - DB_PATH=/app/data/signals.db
      - PORT=8001
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
  logs: